PL_USERNAME = "cgregoire_http_ARo30SE9a8nb"
PL_PASSWORD = "X6JE22K23hIUZIaJ26IFO2senVxF41xP"
PL_API_KEY  = "uiqt3492x3k80mq6fu1197qm"
PL_API_HASH = "1EnaDpxpWnzaSpWK7BZyrsV919UmrTb1kouzooeG3rhabeDHPMteQV3jsaIQh6v3"
